### ISSUE TITLE
styles.css in wrong place and not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#10]
styles.css file should sit within your plugin root so that it can be cached with Moodle's normal css caching processes - that way you don't include it using $PAGE->requires->css and it's just there and cached already.

but .. you also need to make sure your css is very specific - for that reason you should prefix all tags in your styles.css file with:
.block_behaviour 

see other plugins for good examples of this.

This particular one doesn't block approval in the plugins db, but would be good to do.

**Comment by tedkrahn** [comment]
I have moved the styles.css file into the plugin root directory and am no longer using $PAGE to load it. I have also prefixed all the tags with .path-blocks-behaviour, as .block_behaviour was not working. It appears that the prefix I used is for separate pages (only place I use custom CSS), while the prefix you suggested is for CSS in the block itself.
