### ISSUE TITLE
Error messages in debug mode

### ISSUE THREAD

**Issue by canatojr** [Behaviour-Analytics/moodle-block_behaviour#14]
Hi, Ted!

First of all, congratulations on the development of the plugin!

As a way to contribute, I would like to report some problems that I encountered when using it as well as some suggestions.

In this first post I'd like to report that with the debug mode enabled, these lines appear to me on the course page:

```
line 1725 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 1704 of /lib/dml/moodle_database.php: call to moodle_database->get_field_select()
line 157 of /blocks/behaviour/classes/task/increment_logs_schedule.php: call to moodle_database->get_field()
line 93 of /blocks/behaviour/classes/task/increment_logs_schedule.php: call to block_behaviour\task\increment_logs_schedule->get_logs()
line 102 of /blocks/behaviour/block_behaviour.php: call to block_behaviour\task\increment_logs_schedule->update_course()
line 341 of /blocks/moodleblock.class.php: call to block_behaviour->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3953 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 40 of /theme/boost/layout/columns2.php: call to core_renderer->blocks()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 253 of /course/view.php: call to core_renderer->header()
```
In the same way these lines is displayed in administration site area:
```
line 1725 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 1704 of /lib/dml/moodle_database.php: call to moodle_database->get_field_select()
line 113 of /blocks/behaviour/settings.php: call to moodle_database->get_field()
line 99 of /lib/classes/plugininfo/block.php: call to include()
line 81 of /admin/settings/plugins.php: call to core\plugininfo\block->load_settings()
line 8764 of /lib/adminlib.php: call to require()
line 26 of /admin/search.php: call to admin_get_root()
```

Apparently the plug-in is working fine, but it would certainly be much better if these error messages were not displayed, remembering that the messages disappear if the debug mode is disabled.

Best regards!

Osvaldo

**Comment by tedkrahn** [comment]
I am not able to repeat the issue on my system. What version of Moodle are you using and what is the actual error message? It looks there is a DB call to get a field. Is the field missing from the table or is it an error from a missing value?

**Comment by canatojr** [comment]
Hi Ted!

We are using Moodle 3.10+ (Build: 20201113), PHP 7.2.34, mariadb (5.5.5-10.3.27).

I was also unable to repeat the problem on a test site built with an empty database. However, on our official website, the problem continues even after installing the new version of the plugin.

Here is a link to a video I recorded that shows the problem in more detail: https://youtu.be/Kb3XQPUHvGg.

Any idea?

**Comment by tedkrahn** [comment]
Hi Osvaldo,
The error message shows that more than one record was found. The call to get_field() is trying to get the id value of the student archetype from the role table. It seems that your database contains multiple student archetype entries. I find this odd, as I understand there should only be one. What exists for student archetypes in the role table?

**Comment by canatojr** [comment]
You are right, Ted!

We have a second role based on student archetype that works like a non-degree student with some particular permissions.

In fact we work a lot with roles in our site and have some others alternative roles based on teachers, editingteacher and manager archetypes.

**Comment by tedkrahn** [comment]
I have changed the get_field call to use shortname instead of archetype. The shortname is a unique value, so there will always only be one row in the table. This should fix the error.

**Comment by canatojr** [comment]
Great!

**Comment by canatojr** [comment]
Thanks a lot, Ted!
