### ISSUE TITLE
How to reset behavior analysis?

### ISSUE THREAD

**Issue by canatojr** [Behaviour-Analytics/moodle-block_behaviour#15]
Hi!

After some time using the plugin in a course, sometimes happens we have a lot of cluster analysis done and the "replay clustering" pages are filled with a long list of cluster analyzes.

Is there a way to exclude some of these cluster analysis entries?

I realized that even if we delete the block and then add it again, that clusters analysis history remains.

Likewise, if we unenroll a student, his history is still included in the analysis made by the plugin.

So, it would be great if we could reset the entire plugin history.

Sincerelly,
Osvaldo

**Comment by tedkrahn** [comment]
I have had this problem in development as well. Deleting the block from a course does not delete the plugin data associated with that course, which I think it should. But I think that would have to be implemented in Moodle itself. I will work on getting a complete data reset feature and a feature for removing replays. Thanks for using the plugin!

**Comment by tedkrahn** [comment]
I have added two new features to the plugin to delete data. The first is a button in the replay interface to delete the selected clustering data. The other feature is a delete data page that allows for deleting all data for a course. There is clustering data, graph configuration data, and student log data that can be deleted. Deleting all 3 will reset the plugin to the point when it was first installed. These features have been submitted to Moodle and should be available as an update through the plugins directory. Let me know if these work for you and if you have any more issues.

**Comment by canatojr** [comment]
Thank you for this great improvement! It works like a charm!

**Comment by canatojr** [comment]
They are not issues, but I have some suggestions posted here for the first time, which are now transferred to another post.
