### ISSUE TITLE
Blanck page in a specific course

### ISSUE THREAD

**Issue by canatojr** [Behaviour-Analytics/moodle-block_behaviour#16]
Hello!

A new problem is happening in a specific course:

1. Once installed the block in this course (id=12), the click on "View student behaviour" shows the graph for 2 or 3 seconds and then goes to a blank page.

2. No message displayed with debug mode enabled.

3. After some analysis in the moodle-error-log file, I found this line:
`[Sat Jan 16 07:34:01.446857 2021] [php7:notice] [pid 30953] [client XXX] Default exception handler: Erro ao gravar na base de dados Debug: Unknown column 'NAN' in 'field list'\nINSERT INTO mdl_block_behaviour_centroids (courseid,userid,studentid,coordsid,totalx,totaly,numnodes,centroidx,centroidy) VALUES(?,?,?,?,?,?,?,?,?)\n-- line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()\n-- line 545 of /blocks/behaviour/locallib.php: call to mysqli_native_moodle_database->insert_record()\n-- line 579 of /blocks/behaviour/locallib.php: call to block_behaviour_update_student_centroid()\n-- line 104 of /blocks/behaviour/update-coords.php: call to block_behaviour_update_centroids_and_centres()\n[array (\n  0 => 12,\n  1 => '4',\n  2 => '5124',\n  3 => 1610793239407,\n  4 => 0,\n  5 => 0,\n  6 => 0,\n  7 => NAN,\n  8 => NAN,\n)]\nError code: dmlwriteexception\n* line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown\n* line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()\n* line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()\n* line 545 of /blocks/behaviour/locallib.php: call to mysqli_native_moodle_database->insert_record()\n* line 579 of /blocks/behaviour/locallib.php: call to block_behaviour_update_student_centroid()\n* line 104 of /blocks/behaviour/update-coords.php: call to block_behaviour_update_centroids_and_centres()\n, referer: https://XXX/blocks/behaviour/view.php?id=12
`
4. So I logged in as user **'5124'**, navigated through some modules of the course (**id = 12**). After that uninstalled the behavior block, deleted all entries in the behavior database tables and reinstalled the block in that course.

5. Realizing that the problem persisted, I went back to the moodle-error-log, found a new line for another student '9285' and repeated the step described above.

6. Realizing that the problem still persisted, I went back to moodle-error-log again, but now no message is displayed and the click on "Show student behavior" is still returning a blank page with no debug message.

Sincerelly,
Osvaldo

**Comment by tedkrahn** [comment]
I can't repeat this issue on my system. It looks like my program is missing data of some kind, but I'm not sure what. Is there anything about your course 12 that is different from other courses?

**Comment by canatojr** [comment]
Hello, Ted!

I found out why the problem is happening in this particular course: it has only one section, section 0 and the graph is not constructed if the course does not have at least two sections with something in it.

Cheers!

**Comment by tedkrahn** [comment]
I think you are on to something. I have been able to reproduce this issue. I'm not sure why it is happening, but will keep looking. In the meantime, it is possible to delete all the graph configuration data for that course to reset it.

**Comment by canatojr** [comment]
I don't know if this information will help anything, but I just realized that the problem does not happen if the first time the graph is built, the course already had at least two non-empty sections.

To reproduce:
1. In a course insert at least two activities / resources, one within section 0 and the other within section 1
2. Build the graph
3. Delete the activity / resource in section 1
4. Rebuild the graph and you will see that no problem occurs.
5. Now delete all the data and try to build the graph. You will see that the problem is back.

**Comment by tedkrahn** [comment]
I have been able to determine what the problem was and correct it. I have pushed the changes to this repository, but have not yet changed the Moodle plugins directory version. I will update the Moodle version when I have added a group selection feature.
Thank you for taking the time to use the software and report problems and suggestions.

**Comment by canatojr** [comment]
I just tested the new code and everything is fine now.
Thanks!

**Comment by canatojr** [comment]
I just tested the new code and everything is fine now.
Thanks!
