### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#3]
When a plugin includes a 3rd party lib, it must also implement the thirdpartylibs.xml file to cover detials on the libraries that are included.
see more info here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

this is a blocker for approval in the plugins db.

**Comment by tedkrahn** [comment]
I have created a lib/thirdpartylibs.xml file for the included libraries. There is also a readme_moodle.txt file for each library with its original source code.

**Comment by mudrd8mz** [comment]
Please re-open this. For plugins, the said file is supposed to be in the root of the plugin folder (where e.g. the version.php is), not in the lib folder. Only then it is taken into account. 

Having the file here will allow to get much more realistic figures reported by the prechecker.

**Comment by tedkrahn** [comment]
thirdpartylibs.xml has been moved to the root directory
