### ISSUE TITLE
check for $this->content !== null should be moved higher.

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#4]
block_behaviour::get_content() is called twice on each load of a block - for this reason, you need to put the check for $this->content !== null as high as you can - before you make any db calls/updates otherwise this just slows the page down making db calls multiple times.

I think this is probably a blocker for plugins db approval because you have 3 or 4 db calls that occur before this check which will get repeated on every page load - especially the ones like get_logs() which could be pretty expensive.

**Comment by tedkrahn** [comment]
The get_content() function now conducts the null content check before doing anything else.
