### ISSUE TITLE
settings.php should be optimised better

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#5]
at the very least you should be wrapping a lot of that in a check to:
if ($ADMIN->fulltree) {

(see other blocks for an example on this.)

but this also looks quite heavy on the db - with multiple db calls inside various loops - should be possible to optimise that a lot.

**Comment by tedkrahn** [comment]
I have wrapped the settings in a check for $ADMIN->fulltree and have optimized the script to use fewer DB queries.
