### ISSUE TITLE
hard-coded role ids

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#6]
Sites may delete/change roles - relying on hard-coded roles is extremely unreliable and dangerous.
https://github.com/Behaviour-Analytics/moodle-block_behaviour/blob/master/settings.php#L54

this is a definite blocker for approval in the plugins db.

**Comment by tedkrahn** [comment]
I have only used role ids in the user_get_participants() function, which can take 0 as a role id (all users). Function calls that use a role id of 0 are unchanged, while all other calls now first get the required role id from the role table matching on archetype. An example of this is:
$roleid = $DB->get_field('role', 'id', ['archetype' => 'student']);
where the $roleid is then used in the function call in place of a hard-coded value.
