### ISSUE TITLE
please use $DB->get_in_or_equal to avoid sql injection

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#8]
stuff like this:
    foreach ($participants as $key => $value) {
        $oars .= ' userid = '.$value->id.' OR';
    }
    // Remove trailing OR.
    $oars = substr($oars, 0, -2);

should really use the DB->get_in_or_equal function so that you aren't just passing php vars directly into inline code and it reads a lot better too!

**Comment by tedkrahn** [comment]
I have changed all such queries to use the get_in_or_equal function.
