### ISSUE TITLE
undefined vars. 

### ISSUE THREAD

**Issue by danmarsden** [Behaviour-Analytics/moodle-block_behaviour#9]
I see a few places in your code where you just put a var name and then a semicolon eg:
$module;
My IDE highlights these in red - I'd also suspect these to be reporting php debugging notices as well.
You should take a look to make sure your IDE has it's php lint/syntax highlighting.
couple of examples in your export.php file.

**Comment by tedkrahn** [comment]
I do not use a regular IDE, as I prefer Emacs (no such highlighting that I know of), and have seen no debugging notices either. I have used grep to find all unassigned variables and assign them a value, most often null.
